In [1]:
# Import dependencis 

import numpy as np
import pandas as pd 
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler 
from sklearn import svm
from sklearn.metrics import accuracy_score

In [3]:
dataset = pd.read_csv('diabetes.csv') 
dataset.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [4]:
dataset.shape

(768, 9)

In [5]:
# Statestical Summary 

dataset.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [6]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [8]:
# check the balance of outcoume

dataset['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [10]:
# Separate X and Y 

X = dataset.drop(['Outcome'], axis = 1) 
Y = dataset['Outcome']

In [12]:
X

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31
2,8,183,64,0,0,23.3,0.672,32
3,1,89,66,23,94,28.1,0.167,21
4,0,137,40,35,168,43.1,2.288,33
...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63
764,2,122,70,27,0,36.8,0.340,27
765,5,121,72,23,112,26.2,0.245,30
766,1,126,60,0,0,30.1,0.349,47
767,1,93,70,31,0,30.4,0.315,23

In [25]:
# Split Train and Test

X_train, x_test, Y_train, y_test = train_test_split(
    X, Y, test_size = 0.2, stratify=Y, random_state = 6
)

In [26]:
print(X.shape, X_train.shape, x_test.shape)

(768, 8) (614, 8) (154, 8)

In [27]:
#! MAke an oobject of standardscaler 

scaler = StandardScaler()

In [28]:
# standardize train and test data

X_train = scaler.fit_transform(X_train) 
x_test = scaler.transform(x_test)

In [29]:
X_train

array([[ 0.64219117, -0.70666817, -0.47230122, ..., -0.67955696,
         0.10355578, -0.13035418],
       [ 0.34415233, -1.14202398,  0.24423625, ..., -0.40745562,
         2.34162211, -0.13035418],
       [ 0.64219117, -1.07983029,  0.55132373, ..., -1.15897361,
        -1.16786292, -0.13035418],
       ...,
       [-1.14604183, -0.70666817, -3.54317607, ..., -0.92574389,
        -0.64759715, -0.98363205],
       [ 0.34415233, -1.39079873,  0.65368623, ...,  0.47363445,
        -0.94621123,  0.12562919],
       [-0.54996417,  1.03475507,  0.24423625, ..., -0.71842858,
        -0.09346794, -0.55699311]], shape=(614, 8))

In [30]:
x_test

array([[-0.848003  , -3.78525568, -1.08647619, ..., -0.96461551,
        -0.99546716, -0.98363205],
       [-0.54996417,  0.00855923, -0.47230122, ..., -0.30379796,
         0.78082482, -0.98363205],
       [ 0.34415233, -0.30240921, -0.16521373, ...,  0.73277858,
        -0.62296919,  0.63759591],
       ...,
       [ 0.64219117, -0.5822808 ,  0.14187375, ...,  0.71982137,
        -0.42902396,  1.83218494],
       [-0.25192533,  0.25733398, -0.26757623, ..., -1.17193082,
        -0.45980892, -0.98363205],
       [ 0.64219117, -0.92434608, -0.36993872, ..., -0.01873941,
        -1.16478442,  1.06423485]], shape=(154, 8))

In [31]:
# create an object of svm algorithm 

classifier = svm.SVC(kernel = 'linear')

In [32]:
# now train the model 

classifier.fit(X_train, Y_train)

SVC(kernel='linear')

In [36]:
# check the training accuracy 

X_train_prediction = classifier.predict(X_train) 
train_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [38]:
print('Accuracy On Traing Data: ', train_data_accuracy)

Accuracy On Traing Data:  0.7833876221498371

In [40]:
# check the test accuracy

x_test_prediction = classifier.predict(x_test) 
test_data_accuracy = accuracy_score(x_test_prediction, y_test)

In [41]:
print('Accuracy On test data: ', test_data_accuracy)

Accuracy On test data:  0.7987012987012987

In [61]:
# defining an function to predict diabetic 
columns = [
    'Pregnancies',
    'Glucose',
    'BloodPressure',
    'SkinThickness',
    'Insulin',
    'BMI',
    'DiabetesPedigreeFunction',
    'Age'
]


def predict_diabetes(new_patient):
    # convert to DataFrame 
    df = pd.DataFrame([new_patient], columns=columns)
    # standardize input data
    std_data = scaler.transform(df)
    # prediction
    prediction = classifier.predict(std_data)

    if prediction[0] == 0:
        return "Patient is Not Diabetic"
    else:
        return "Patient is Diabetic"

In [71]:
# test on new patient 1 
patient1 = (5,166,72,19,175,25.8,0.587,51)

predict_diabetes(patient1)

'Patient is Diabetic'

In [65]:
patient2 = (1, 85, 66, 29, 0, 26.6, 0.351, 31) 

predict_diabetes (patient2)

'Patient is Not Diabetic'

In [66]:
patient3 = (8, 183, 64, 0, 0, 23.3, 0.672, 32)

predict_diabetes(patient3)

'Patient is Diabetic'

In [68]:
patient4 = (5, 166, 72, 19, 175, 25.8, 0.587, 51) 

predict_diabetes(patient4)

'Patient is Diabetic'

In [69]:
patient5 = (0, 95, 70, 20, 80, 24.5, 0.250, 22) 

predict_diabetes(patient5)

'Patient is Not Diabetic'

In [70]:
patient6 = (7, 150, 78, 35, 200, 36.5, 0.800, 45) 

predict_diabetes(patient6)

'Patient is Diabetic'